def gpa_getter():
    percent = float(input("Please enter your grade as a percent: "))
    if percent >= 95:
        gpa = 4.0
    elif percent >= 94:
        gpa = 3.9
    elif percent >= 93:
        gpa = 3.8
    elif percent >= 92:
        gpa = 3.7
    elif percent >= 91:
        gpa = 3.6
    elif percent >= 90:
        gpa = 3.5
    elif percent >= 89:
        gpa = 3.4
    elif percent >= 88:
        gpa = 3.3
    elif percent >= 87:
        gpa = 3.2
    elif percent >= 86:
        gpa = 3.1
    elif percent >= 85:
        gpa = 3.0
    elif percent >= 84:
        gpa = 2.9
    elif percent >= 83:
        gpa = 2.8
    elif percent >= 82:
        gpa = 2.7
    elif percent >= 81:
        gpa = 2.6
    elif percent >= 80:
        gpa = 2.5
    elif percent >= 79:
        gpa = 2.4
    elif percent >= 78:
        gpa = 2.3
    elif percent >= 77:
        gpa = 2.2
    elif percent >= 76:
        gpa = 2.1
    elif percent >= 75:
        gpa = 2.0
    elif percent >= 74:
        gpa = 1.9
    elif percent >= 73:
        gpa = 1.8
    elif percent >= 72:
        gpa = 1.7
    elif percent >= 71:
        gpa = 1.6
    elif percent >= 70:
        gpa = 1.5
    elif percent >= 69:
        gpa = 1.4
    elif percent >= 68:
        gpa = 1.3
    elif percent >= 67:
        gpa = 1.2
    elif percent >= 66:
        gpa = 1.1
    elif percent >= 65:
        gpa = 1.0   
    else:
        gpa = 0.0
    print("Your GPA is: ", gpa)
gpa_getter()
